import ReactMarkdown from "react-markdown";


const ScientificReport = ({
    reportMarkdown = ""
}) => {

    return (

        <div
            style={{
                background: "#11151d",
                border: "1px solid #272d39",
                borderRadius: "12px",
                padding: "28px"
            }}
        >

            <div
                style={{
                    marginBottom: "24px",
                    paddingBottom: "18px",
                    borderBottom: "1px solid #272d39"
                }}
            >

                <p
                    style={{
                        margin: "0 0 7px",
                        color: "#7f8999",
                        fontSize: "12px",
                        letterSpacing: "1px",
                        textTransform: "uppercase"
                    }}
                >

                    AI Generated

                </p>


                <h2
                    style={{
                        margin: 0,
                        color: "#ffffff"
                    }}
                >

                    Scientific Investigation Report

                </h2>

            </div>


            {
                reportMarkdown
                    ? (

                        <div
                            style={{
                                color: "#b0b8c7",
                                lineHeight: "1.8",
                                fontSize: "15px"
                            }}
                        >

                            <ReactMarkdown>

                                {reportMarkdown}

                            </ReactMarkdown>

                        </div>

                    )
                    : (

                        <p
                            style={{
                                color: "#7f8797"
                            }}
                        >

                            No scientific report content available.

                        </p>

                    )
            }


            <div
                style={{
                    marginTop: "28px",
                    padding: "15px",
                    background: "#0d1118",
                    border: "1px solid #242b36",
                    borderRadius: "8px",
                    color: "#858e9e",
                    fontSize: "12px",
                    lineHeight: "1.6"
                }}
            >

                This report is generated by Fluxor as an AI-assisted
                scientific investigation. Candidate anomaly scores and
                AI confidence values should not be interpreted as
                calibrated probabilities of astronomical discovery.
                Final scientific interpretation requires human review.

            </div>

        </div>
    );
};


export default ScientificReport;